'use client';

import { useState, useEffect } from 'react';
import Header from '@/components/Header';
import { EligibilityData } from '@/types/student';

export default function EligibilityPage() {
    const [students, setStudents] = useState<EligibilityData[]>([]);
    const [searchQuery, setSearchQuery] = useState('');
    const [matchedStudent, setMatchedStudent] = useState<EligibilityData | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [showConfetti, setShowConfetti] = useState(false);
    const [suggestions, setSuggestions] = useState<EligibilityData[]>([]);
    const [showSuggestions, setShowSuggestions] = useState(false);

    useEffect(() => {
        const fetchData = async () => {
            try {
                const response = await fetch('/api/eligibility');
                if (!response.ok) throw new Error('Failed to fetch data');
                const data = await response.json();
                if (data.success) {
                    setStudents(data.data);
                }
            } catch (err) {
                console.error(err);
                setError('Unable to load eligibility data');
            } finally {
                setIsLoading(false);
            }
        };

        fetchData();
    }, []);

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value;
        setSearchQuery(value);
        setMatchedStudent(null);
        setShowConfetti(false);

        if (value.trim().length > 0) {
            const lowerValue = value.toLowerCase();
            const filtered = students.filter(s =>
                s.registrationNumber.toLowerCase().includes(lowerValue) ||
                s.name.toLowerCase().includes(lowerValue)
            ).slice(0, 5); // Limit to 5 suggestions
            setSuggestions(filtered);
            setShowSuggestions(true);
        } else {
            setSuggestions([]);
            setShowSuggestions(false);
        }
    };

    const handleSuggestionClick = (student: EligibilityData) => {
        setSearchQuery(student.registrationNumber);
        setSuggestions([]);
        setShowSuggestions(false);
        setMatchedStudent(student);
        setShowConfetti(true);
        setShowConfetti(true);
        // Confetti will play continuously
        // setTimeout(() => setShowConfetti(false), 5000);
    };

    const handleSearch = () => {
        if (!searchQuery.trim()) {
            setMatchedStudent(null);
            setShowConfetti(false);
            return;
        }

        const lowerQuery = searchQuery.toLowerCase();
        const match = students.find(
            s =>
                s.registrationNumber.toLowerCase() === lowerQuery ||
                s.name.toLowerCase().includes(lowerQuery)
        );

        if (match) {
            setMatchedStudent(match);
            setShowConfetti(true);
            // Confetti will play continuously as long as matchedStudent is present
            // setTimeout(() => setShowConfetti(false), 5000);
        } else {
            setMatchedStudent(null);
            setShowConfetti(false);
        }
        setShowSuggestions(false);
    };

    return (
        <main className="main-layout">
            <Header
                showNav={false}
                subtitle="2025 - Convocation Eligibility Check"
            />

            {showConfetti && <div className="confetti-container">
                {/* Confetti pieces will be generated by CSS */}
                {[...Array(50)].map((_, i) => (
                    <div key={i} className="confetti-piece" style={{
                        left: `${Math.random() * 100}%`,
                        animationDelay: `${Math.random() * 3}s`,
                        animationIterationCount: 'infinite',
                        backgroundColor: ['#ff0000', '#00ff00', '#0000ff', '#ffff00', '#ff00ff'][Math.floor(Math.random() * 5)]
                    }}></div>
                ))}
            </div>}

            <div className="container content-container">
                <div className="page-header">
                    <div>
                        <h1 className="page-title">Convocation Eligibility Check</h1>
                        <p className="page-description">
                            If your details are not found in the search results, you are not eligible for the Convocation 2025.
                        </p>
                    </div>
                </div>

                <div className="search-container" style={{ maxWidth: '600px', margin: '0 auto 40px', position: 'relative' }}>
                    <div className="search-wrapper">
                        <div className="search-icon">
                            <svg style={{ width: '18px', height: '18px' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                            </svg>
                        </div>
                        <input
                            type="text"
                            value={searchQuery}
                            onChange={handleInputChange}
                            onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                            placeholder="Enter Registration Number or Name..."
                            className="search-input"
                            onBlur={() => setTimeout(() => setShowSuggestions(false), 200)}
                            onFocus={() => searchQuery && setShowSuggestions(true)}
                        />
                        <button
                            onClick={handleSearch}
                            className="submit-btn"
                            style={{ marginLeft: '12px' }}
                        >
                            Check
                        </button>
                    </div>

                    {/* Suggestions Dropdown */}
                    {showSuggestions && suggestions.length > 0 && (
                        <div style={{
                            position: 'absolute',
                            top: '100%',
                            left: 0,
                            right: 0,
                            backgroundColor: 'white',
                            border: '1px solid #e5e7eb',
                            borderRadius: '8px',
                            marginTop: '4px',
                            boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                            zIndex: 50,
                            maxHeight: '300px',
                            overflowY: 'auto'
                        }}>
                            {suggestions.map((student) => (
                                <div
                                    key={student.id}
                                    onClick={() => handleSuggestionClick(student)}
                                    style={{
                                        padding: '12px 16px',
                                        cursor: 'pointer',
                                        borderBottom: '1px solid #f3f4f6',
                                        transition: 'background-color 0.2s'
                                    }}
                                    onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#f9fafb'}
                                    onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'white'}
                                >
                                    <div style={{ fontWeight: 600, color: '#1f2937' }}>{student.name}</div>
                                    <div style={{ fontSize: '12px', color: '#6b7280' }}>{student.registrationNumber}</div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                {isLoading && (
                    <div className="loading-container">
                        <div className="loading-spinner"></div>
                        <p style={{ marginTop: '16px', fontSize: '14px', color: '#6b7280' }}>Loading data...</p>
                    </div>
                )}

                {error && (
                    <div className="error-container">
                        <p style={{ color: '#dc2626' }}>{error}</p>
                    </div>
                )}

                {matchedStudent && (
                    <div className="eligibility-card fade-in-up">
                        <div className="congrats-header">
                            <span className="congrats-icon">🎓</span>
                            <h2>Congratulations!</h2>
                            <p>You are eligible for Convocation 2025</p>
                        </div>

                        <div className="student-details">
                            <div className="degree-title">
                                {matchedStudent.degreeType.toLowerCase().includes('special')
                                    ? 'BSc in Applied Accounting Honours Degree'
                                    : 'BSc in Applied Accounting General Degree'}
                            </div>
                            <div className="detail-row">
                                <span className="detail-label">Name:</span>
                                <span className="detail-value">{matchedStudent.name}</span>
                            </div>
                            <div className="detail-row">
                                <span className="detail-label">Registration Number:</span>
                                <span className="detail-value">{matchedStudent.registrationNumber}</span>
                            </div>
                            <div className="detail-row">
                                <span className="detail-label">Degree Type:</span>
                                <span className="detail-value highlight">{matchedStudent.degreeType}</span>
                            </div>
                            <div className="detail-row">
                                <span className="detail-label">GPA:</span>
                                <span className="detail-value highlight">{matchedStudent.gpa}</span>
                            </div>
                            <div className="detail-row">
                                <span className="detail-label">Class Award:</span>
                                <span className="detail-value highlight">{matchedStudent.classAward}</span>
                            </div>
                        </div>
                        <div style={{ marginTop: '20px', fontSize: '12px', fontStyle: 'italic', color: 'red', textAlign: 'center' }}>
                            *This is a System-generated report. Its validity is subject to verification by the Examination Department, SAB Campus of CA Sri Lanka.
                        </div>
                    </div>
                )}

                {!matchedStudent && searchQuery && !isLoading && !error && (
                    <div style={{ textAlign: 'center', marginTop: '20px', color: '#6b7280' }}>
                        <p>No matching record found. Please check your details and try again.</p>
                    </div>
                )}
            </div>
        </main>
    );
}
